### ISSUE TITLE
Select components should include selected prop

### ISSUE THREAD

**Issue by homoky** [interval/interval-node#13]
There should be an option to predefine default state of checked items for `io.select` components. 

Example: You want upsert users in account, you have to click every user on upsert, not only adding / removing ones.

**Comment by jacobmischka** [comment]
This can currently be done with the `defaultValue` property, please see the docs page for an example: https://interval.com/docs/io-methods/select-multiple

Agree that this isn't ideal though, because it requires you to basically redefine options instead of setting a `selected` flag which would make more sense. This has been on our radar to adjust for a while, thanks for bringing it back to our attention!
