### ISSUE TITLE
[idea] Option to change pagination on table 

### ISSUE THREAD

**Issue by homoky** [interval/interval-node#6]
Would be cool to have option to control pagination on table or even disable it completly.

**Comment by alexarena** [comment]
We love this idea, it's been on our todo list for a while now. Here's what we're thinking from an API perspective: we'd add a new prop to all of the table methods called `defaultRowsPerPage`. Our "weird" idea is that you could disable pagination by setting `defaultRowsPerPage` to [Infinity](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity). Infinity is rarely used intentionally, so that's why it feels weird to us, but it's also semantically correct.

**Comment by jacobmischka** [comment]
Added in [0.26.0](https://interval.com/changelog/0-26-0), thanks for reminding us and putting this back at the top of our list!
